2.1 Neural Network Link Weights

Reference
> Make Your Own Neural Network by Tariq Rashid

> https://github.com/makeyourownneuralnetwork

IDE
> Google Colab

> https://colab.research.google.com




Link Weights are the heart of a neural network.

They are:

> used to calculate the signal forward through the network

> used to calculate the error back through the network (propogation)

> refined to improve network performance

Let's start by making a 3 x 3 matrix, populated with random numbers, via numpy

In [1]:
import numpy as np

np.random.rand(3,3)

array([[0.40112211, 0.80231345, 0.72431981],
       [0.61093238, 0.47674953, 0.60810907],
       [0.9891461 , 0.53436667, 0.03680993]])

Let's expand the 3 x 3 matrix and include negative numbers

We will subtract 0.5 from each value in order to have a mix of positive and negative values.

In [4]:
np.random.rand(3,3) - 0.5

array([[-0.23433991, -0.22797524, -0.74242043],
       [-0.52033174, -0.54886771, -0.89134583],
       [-0.92902025, -0.31122926, -0.15464158]])

If we subtract 1 from each value, all of the random numbers will be negative and this will not work as we wish.

In [5]:
np.random.rand(3,3) - 1

array([[-0.08206902, -0.46064424, -0.59457197],
       [-0.64724137, -0.33183851, -0.34814854],
       [-0.3929059 , -0.83912145, -0.48452362]])

We will use this idea as a building block in our future work on neural networks